#!/bin/sh

# IMPORTANT: If you modify this file, run this command to keep execution permissions:
# git add --chmod=+x .husky/pre-push

. "$(dirname "$0")/_/husky.sh"

bash .ci-cd/versionize-and-push.sh

## husky task runner examples ------------------
## Note : for local installation use 'dotnet' prefix. e.g. 'dotnet husky'

## run all tasks
#husky run

### run all tasks with group: 'group-name'
#husky run --group group-name

## run task with name: 'task-name'
#husky run --name task-name

## pass hook arguments to task
#husky run --args "$1" "$2"

## or put your custom commands ------------------
#echo 'Husky.Net is awesome!'

#dotnet husky run
