name: Release NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write
  id-token: write   # required for nuget.org OIDC

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Restore local tools
        run: dotnet tool restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Bump version and changelog
        run: |
          dotnet tool run versionize --skip-commit-message-check
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md **/*.csproj
          git commit -m "chore: bump version [skip ci]" || echo "No changes to commit"
          git push

      - name: Pack NuGet package
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Publish to NuGet
        run: dotnet nuget push ./nupkg/*.nupkg \
             --api-key ${{ NUGET_AUTH_TOKEN }} \
             --source https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN  }}
