name: Release NuGet Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.100-rc.1.25451.107'

      - name: Restore dependencies
        run: dotnet restore

      - name: Restore local tools
        run: dotnet tool restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Bump version and changelog
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          dotnet tool run versionize --skip-commit-message-check
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git add -A "*.csproj"
          git commit -m "chore: bump version [skip ci]" || echo "No changes to commit"
          git push --follow-tags

      - name: Pack NuGet package
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: dotnet pack --configuration Release --output ./nupkg

      - name: Publish to NuGet (trusted publishing)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          dotnet nuget push ./nupkg/*.nupkg \
               --source https://api.nuget.org/v3/index.json \
               --skip-duplicate
